 const dataesthead = [
  {
    "course_id": 1,
    "course_title": "IT Fundamentals - Everything you need to know about IT",
    "course_instructor_name": "Imran Afzal",
    "skills_you_gain": "Computer Skills -- Great help for passing CompTIA A+ (220-1001) and ITF+ (FCO-U61)",
    "total_course_mins": 690.0,
    "total_no_of_lectures": 151.0,
    "ratings": 4.6,
    "total_reviews": "3907",
    "course_levels": "All Levels",
    "course_links": "https://www.udemy.com/course/it-fundamentals-everything-you-need-to-know-about-it/",
    "course_thumbnail_image": "https://img-c.udemycdn.com/course/240x135/3627542_1828_3.jpg",
    "raw_text": "IT Fundamentals - Everything you need to know about IT Computer Skills -- Great help for passing CompTIA A+ (220-1001) and ITF+ (FCO-U61) All Levels",
    "clean_text": "Fundamentals need know Computer Skills great help pass CompTIA A+ 220 1001 ITF+ FCO U61 Levels"
  },
  {
    "course_id": 2,
    "course_title": "IT Support Technical Skills Bootcamp",
    "course_instructor_name": "Jobskillshare Community",
    "skills_you_gain": "Hands-on Technical skills for  Support Professionals",
    "total_course_mins": 2310.0,
    "total_no_of_lectures": 75.0,
    "ratings": 4.4,
    "total_reviews": "1338",
    "course_levels": "Beginner",
    "course_links": "https://www.udemy.com/course/it-support-technical-skills-training-part-1/",
    "course_thumbnail_image": "https://img-b.udemycdn.com/course/240x135/4663104_fa14.jpg",
    "raw_text": "IT Support Technical Skills Bootcamp Hands-on Technical skills for  Support Professionals Beginner",
    "clean_text": "Support Technical Skills Bootcamp Hands Technical skill   Support Professionals Beginner"
  },
{
    "course_id": 3,
    "course_title": "IT for beginners | IT for dummies | IT for non-IT",
    "course_instructor_name": "Maaike van Putten",
    "skills_you_gain": "Everything all non-technical professionals in an  environment should know.",
    "total_course_mins": 90.0,
    "total_no_of_lectures": 32.0,
    "ratings": 4.3,
    "total_reviews": "2242",
    "course_levels": "Beginner",
    "course_links": "https://www.udemy.com/course/it-for-beginners/",
    "course_thumbnail_image": "https://img-b.udemycdn.com/course/240x135/1976202_efaf.jpg",
    "raw_text": "IT for beginners | IT for dummies | IT for non-IT Everything all non-technical professionals in an  environment should know. Beginner",
    "clean_text": "beginner | dummy | non non technical professional   environment know beginner"
  },
  {
    "course_id": 4,
    "course_title": "IT Support Fundamentals for IT Beginners",
    "course_instructor_name": "Jobskillshare Community",
    "skills_you_gain": "Support Skills for  Beginners",
    "total_course_mins": 900.0,
    "total_no_of_lectures": 53.0,
    "ratings": 4.4,
    "total_reviews": "173",
    "course_levels": "Beginner",
    "course_links": "https://www.udemy.com/course/it-support-fundamentals-for-it-beginners/",
    "course_thumbnail_image": "https://img-c.udemycdn.com/course/240x135/4714828_90b7.jpg",
    "raw_text": "IT Support Fundamentals for IT Beginners Support Skills for  Beginners Beginner",
    "clean_text": "Support Fundamentals Beginners Support Skills   Beginners Beginner"
  },
  {
    "course_id": 5,
    "course_title": "Desktop IT Support Level 1 & 2 in real life (Troubleshooting",
    "course_instructor_name": "Tareq Tech",
    "skills_you_gain": "Learn everything in real life Troubleshooting for  Help Desk , Helpdesk ,  Support , System Administration and",
    "total_course_mins": 450.0,
    "total_no_of_lectures": 60.0,
    "ratings": 4.1,
    "total_reviews": "1343",
    "course_levels": "Beginner",
    "course_links": "https://www.udemy.com/course/desktop-support/",
    "course_thumbnail_image": "https://img-c.udemycdn.com/course/240x135/2511848_e5e3_4.jpg",
    "raw_text": "Desktop IT Support Level 1 & 2 in real life (Troubleshooting Learn everything in real life Troubleshooting for  Help Desk , Helpdesk ,  Support , System Administration and Beginner",
    "clean_text": "desktop Support Level 1 2 real life troubleshooting learn real life troubleshoot   Help Desk Helpdesk   Support System Administration Beginner"
  },
  {
    "course_id": 6,
    "course_title": "CompTIA IT Fundamentals (ITF+) Complete Course (FC0-U61)",
    "course_instructor_name": "Mike Chapple, Ph.D.",
    "skills_you_gain": "Everything you need to know to pass the CompTIA  ITF+ exam and start your career in ! Fully updated for the 2022 exam!",
    "total_course_mins": 240.0,
    "total_no_of_lectures": 69.0,
    "ratings": 4.7,
    "total_reviews": "1330",
    "course_levels": "Beginner",
    "course_links": "https://www.udemy.com/course/certmike-comptia-it-fundamentals-itf/",
    "course_thumbnail_image": "https://img-c.udemycdn.com/course/240x135/4161962_2316.jpg",
    "raw_text": "CompTIA IT Fundamentals (ITF+) Complete Course (FC0-U61) Everything you need to know to pass the CompTIA  ITF+ exam and start your career in ! Fully updated for the 2022 exam! Beginner",
    "clean_text": "comptia Fundamentals ITF+ Complete Course FC0 U61 need know pass comptia   ITF+ exam start career fully update 2022 exam beginner"
  },
  {
    "course_id": 7,
    "course_title": "Learning IT Help Desk for Beginners",
    "course_instructor_name": "Emilio Aguero",
    "skills_you_gain": "Must know skills for Helpdesk and Service Desk Professionals!!",
    "total_course_mins": 270.0,
    "total_no_of_lectures": 27.0,
    "ratings": 4.5,
    "total_reviews": "777",
    "course_levels": "All Levels",
    "course_links": "https://www.udemy.com/course/helpdesk-pro/",
    "course_thumbnail_image": "https://img-b.udemycdn.com/course/240x135/3935176_4d6b.jpg",
    "raw_text": "Learning IT Help Desk for Beginners Must know skills for Helpdesk and Service Desk Professionals!! All Levels",
    "clean_text": "learn help Desk Beginners know skill Helpdesk Service Desk professional level"
  },
  {
    "course_id": 8,
    "course_title": "Complete Linux Training Course to Get Your Dream IT Job 2023",
    "course_instructor_name": "Imran Afzal",
    "skills_you_gain": "The BEST Linux Administration course that prepares you for corporate jobs and for RHCSA, RHCE, LFCS, CLNP certifications",
    "total_course_mins": 2130.0,
    "total_no_of_lectures": 257.0,
    "ratings": 4.6,
    "total_reviews": "26868",
    "course_levels": "All Levels",
    "course_links": "https://www.udemy.com/course/complete-linux-training-course-to-get-your-dream-it-job/",
    "course_thumbnail_image": "https://img-b.udemycdn.com/course/240x135/1523066_334c_14.jpg",
    "raw_text": "Complete Linux Training Course to Get Your Dream IT Job 2023 The BEST Linux Administration course that prepares you for corporate jobs and for RHCSA, RHCE, LFCS, CLNP certifications All Levels",
    "clean_text": "Complete Linux Training Course dream Job 2023 BEST Linux Administration course prepare corporate job RHCSA RHCE LFCS clnp certification Levels"
  },
  {
    "course_id": 9,
    "course_title": "TOTAL: CompTIA IT Fundamentals ITF+ (FCO-U61).",
    "course_instructor_name": "Total Seminars \u2022 Over 1 Million Enrollments, Scott Jernigan",
    "skills_you_gain": "What EVERY USER needs to know about basic  concepts, troubleshooting devices, and identifying/preventing security risk",
    "total_course_mins": 300.0,
    "total_no_of_lectures": 64.0,
    "ratings": 4.6,
    "total_reviews": "10243",
    "course_levels": "Beginner",
    "course_links": "https://www.udemy.com/course/it-fundamentals-fc0-u61-the-total-course/",
    "course_thumbnail_image": "https://img-c.udemycdn.com/course/240x135/1302896_f34e_2.jpg",
    "raw_text": "TOTAL: CompTIA IT Fundamentals ITF+ (FCO-U61). What EVERY USER needs to know about basic  concepts, troubleshooting devices, and identifying/preventing security risk Beginner",
    "clean_text": "total CompTIA Fundamentals ITF+ FCO U61 USER need know basic   concept troubleshooting device identify prevent security risk Beginner"
  },
  {
    "course_id": 10,
    "course_title": "CompTIA Mastery: A+, Network+, Security+ Ultimate Bundle",
    "course_instructor_name": "PaceIT Academy, M. Fahmid Chowdhury",
    "skills_you_gain": "ALL in ONE : CompTIA A+, CompTIA Network+. CompTIA Security+ Accelerate Your  Career!",
    "total_course_mins": 1380.0,
    "total_no_of_lectures": 183.0,
    "ratings": 4.3,
    "total_reviews": "332",
    "course_levels": "All Levels",
    "course_links": "https://www.udemy.com/course/computer-network-course/",
    "course_thumbnail_image": "https://img-c.udemycdn.com/course/240x135/4309362_e221_6.jpg",
    "raw_text": "CompTIA Mastery: A+, Network+, Security+ Ultimate Bundle ALL in ONE : CompTIA A+, CompTIA Network+. CompTIA Security+ Accelerate Your  Career! All Levels",
    "clean_text": "comptia Mastery A+ Network+ Security+ Ultimate Bundle CompTIA A+ CompTIA Network+ CompTIA Security+ Accelerate   Career level"
  }
]

 export default dataesthead;